-- V11__Adaptive_Regime_Persistent.sql
-- Persist AdaptiveRegimeEngine config in the database.
-- Previously the config was written to adaptive_regime.json in the container working directory,
-- which is wiped on every Render deploy — so learned parameters were silently discarded.
-- This table stores the single live config row (id=1) plus a full history for audit.

CREATE TABLE IF NOT EXISTS adaptive_regime_config (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    min_regime_score        INTEGER NOT NULL DEFAULT 4,
    min_or_range            DOUBLE PRECISION NOT NULL DEFAULT 120.0,
    min_atr_ratio           DOUBLE PRECISION NOT NULL DEFAULT 1.10,
    min_efficiency          DOUBLE PRECISION NOT NULL DEFAULT 0.55,
    min_breakout_hold_rate  DOUBLE PRECISION NOT NULL DEFAULT 0.50,
    last_updated            TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    notes                   VARCHAR(256)
);

-- Seed the default row (id=1) which AdaptiveRegimeEngine will upsert
INSERT INTO adaptive_regime_config
    (id, min_regime_score, min_or_range, min_atr_ratio, min_efficiency, min_breakout_hold_rate, notes)
VALUES
    (1, 4, 120.0, 1.10, 0.55, 0.50, 'seed-defaults')
ON CONFLICT (id) DO NOTHING;

COMMENT ON TABLE adaptive_regime_config IS
    'Single-row (id=1) live adaptive regime parameters. Survives container restarts.';
