-- V1: Initial RiskPilot schema.

CREATE TABLE IF NOT EXISTS trading_sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_date DATE NOT NULL UNIQUE,
    symbol VARCHAR(20) NOT NULL,
    daily_open DECIMAL(10, 2) NOT NULL,
    or_high DECIMAL(10, 2) NOT NULL,
    or_low DECIMAL(10, 2) NOT NULL,
    or_expansion DECIMAL(10, 2) NOT NULL,
    fast_candle_exists BOOLEAN NOT NULL DEFAULT FALSE,
    regime VARCHAR(20) NOT NULL DEFAULT 'DEAD',
    regime_locked BOOLEAN NOT NULL DEFAULT FALSE,
    trades_generated INTEGER NOT NULL DEFAULT 0,
    trades_executed INTEGER NOT NULL DEFAULT 0,
    trades_rejected INTEGER NOT NULL DEFAULT 0,
    total_pn_l DECIMAL(12, 2) NOT NULL DEFAULT 0,
    max_drawdown DECIMAL(12, 2) NOT NULL DEFAULT 0,
    max_profit DECIMAL(12, 2) NOT NULL DEFAULT 0,
    session_active BOOLEAN NOT NULL DEFAULT TRUE,
    day_blocked_by_first_trade_failure BOOLEAN NOT NULL DEFAULT FALSE,
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    notes VARCHAR(500),
    session_start TIMESTAMP NOT NULL,
    session_end TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_sessions_symbol_date ON trading_sessions(symbol, session_date);
CREATE INDEX IF NOT EXISTS idx_sessions_active ON trading_sessions(session_active);
CREATE INDEX IF NOT EXISTS idx_sessions_date ON trading_sessions(session_date);

CREATE TABLE IF NOT EXISTS trades (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    symbol VARCHAR(20) NOT NULL,
    direction VARCHAR(10) NOT NULL,
    entry_price DECIMAL(10, 2) NOT NULL,
    stop_loss DECIMAL(10, 2) NOT NULL,
    target_price DECIMAL(10, 2) NOT NULL,
    position_size DECIMAL(5, 2) NOT NULL,
    remaining_size DECIMAL(5, 2) NOT NULL,
    realized_pn_l DECIMAL(10, 2) NOT NULL DEFAULT 0,
    unrealized_pn_l DECIMAL(10, 2) NOT NULL DEFAULT 0,
    max_favorable_excursion DECIMAL(10, 2) NOT NULL DEFAULT 0,
    max_adverse_excursion DECIMAL(10, 2) NOT NULL DEFAULT 0,
    tp1hit BOOLEAN NOT NULL DEFAULT FALSE,
    runner_active BOOLEAN NOT NULL DEFAULT FALSE,
    tail_half_locked BOOLEAN NOT NULL DEFAULT FALSE,
    trailing_stop_loss DECIMAL(10, 2) NOT NULL DEFAULT 0,
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    exit_reason VARCHAR(50) NOT NULL DEFAULT 'NONE',
    entry_time TIMESTAMP NOT NULL,
    exit_time TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_trades_symbol_status ON trades(symbol, status);
CREATE INDEX IF NOT EXISTS idx_trades_entry_time ON trades(entry_time);
CREATE INDEX IF NOT EXISTS idx_trades_exit_time ON trades(exit_time);

CREATE TABLE IF NOT EXISTS candles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    symbol VARCHAR(20) NOT NULL,
    date DATE NOT NULL,
    timestamp TIMESTAMP NOT NULL,
    open_price DECIMAL(10, 2) NOT NULL,
    high_price DECIMAL(10, 2) NOT NULL,
    low_price DECIMAL(10, 2) NOT NULL,
    close_price DECIMAL(10, 2) NOT NULL,
    volume BIGINT NOT NULL,
    range DECIMAL(10, 2),
    timeframe INTEGER,
    is_bullish BOOLEAN,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_candles_symbol_time ON candles(symbol, timestamp);
CREATE INDEX IF NOT EXISTS idx_candles_date ON candles(date);
CREATE INDEX IF NOT EXISTS idx_candles_timeframe ON candles(timeframe);

CREATE TABLE IF NOT EXISTS trading_signals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    symbol VARCHAR(20) NOT NULL,
    direction VARCHAR(10) NOT NULL,
    expected_entry DECIMAL(10, 2) NOT NULL,
    stop_loss DECIMAL(10, 2) NOT NULL,
    target_price DECIMAL(10, 2) NOT NULL,
    confidence INTEGER NOT NULL DEFAULT 50,
    risk_amount DECIMAL(10, 2) NOT NULL,
    reward_amount DECIMAL(10, 2) NOT NULL,
    risk_reward_ratio DECIMAL(5, 2) NOT NULL,
    regime VARCHAR(20) NOT NULL,
    time_phase VARCHAR(20) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'GENERATED',
    rejection_reason VARCHAR(100),
    signal_time TIMESTAMP NOT NULL,
    execution_time TIMESTAMP,
    execution_latency_seconds DECIMAL(8, 3),
    actual_entry DECIMAL(10, 2),
    entry_slippage DECIMAL(5, 2),
    strategy VARCHAR(50),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_signals_symbol_time ON trading_signals(symbol, signal_time);
CREATE INDEX IF NOT EXISTS idx_signals_status ON trading_signals(status);
CREATE INDEX IF NOT EXISTS idx_signals_regime ON trading_signals(regime);
CREATE INDEX IF NOT EXISTS idx_signals_strategy ON trading_signals(strategy);
