-- V2: Add tick data tracking.

CREATE TABLE IF NOT EXISTS tick_data (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    symbol VARCHAR(20) NOT NULL,
    price DECIMAL(10, 2) NOT NULL,
    volume BIGINT NOT NULL,
    sequence_id BIGINT,
    received_at TIMESTAMP NOT NULL,
    processed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    feed_stable BOOLEAN DEFAULT TRUE
);

CREATE INDEX IF NOT EXISTS idx_tick_symbol_received ON tick_data(symbol, received_at);
CREATE INDEX IF NOT EXISTS idx_tick_sequence ON tick_data(sequence_id);
