-- V3: Add kill switch log table.

CREATE TABLE IF NOT EXISTS kill_switch_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    triggered BOOLEAN NOT NULL,
    reasons VARCHAR(500),
    timestamp TIMESTAMP NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_kill_switch_timestamp ON kill_switch_log(timestamp);
