ALTER TABLE trades ADD COLUMN IF NOT EXISTS quantity INTEGER NOT NULL DEFAULT 0;
ALTER TABLE trades ADD COLUMN IF NOT EXISTS remaining_quantity INTEGER NOT NULL DEFAULT 0;
ALTER TABLE trades ADD COLUMN IF NOT EXISTS lot_size INTEGER NOT NULL DEFAULT 1;
ALTER TABLE trades ADD COLUMN IF NOT EXISTS point_value NUMERIC(10, 2) NOT NULL DEFAULT 1.00;
ALTER TABLE trades ADD COLUMN IF NOT EXISTS signal_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE trade_logs ADD COLUMN IF NOT EXISTS quantity INTEGER;
ALTER TABLE trade_logs ADD COLUMN IF NOT EXISTS remaining_quantity INTEGER;
ALTER TABLE trade_logs ADD COLUMN IF NOT EXISTS lot_size INTEGER;
ALTER TABLE trade_logs ADD COLUMN IF NOT EXISTS point_value DOUBLE PRECISION;
ALTER TABLE trade_logs ADD COLUMN IF NOT EXISTS recovery BOOLEAN;

ALTER TABLE trading_sessions ADD COLUMN IF NOT EXISTS realized_pnl NUMERIC(12, 2) NOT NULL DEFAULT 0.00;
ALTER TABLE trading_sessions ADD COLUMN IF NOT EXISTS unrealized_pnl NUMERIC(12, 2) NOT NULL DEFAULT 0.00;
ALTER TABLE trading_sessions ADD COLUMN IF NOT EXISTS account_equity NUMERIC(12, 2) NOT NULL DEFAULT 0.00;
