-- V5: Add correlation ID tracking for trade operations.

CREATE TABLE IF NOT EXISTS trade_correlation_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    correlation_id VARCHAR(16) NOT NULL,
    trade_id VARCHAR(50),
    operation VARCHAR(20) NOT NULL,
    status VARCHAR(20) NOT NULL,
    timestamp TIMESTAMP NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_trade_correlation ON trade_correlation_log(correlation_id);
CREATE INDEX IF NOT EXISTS idx_trade_correlation_timestamp ON trade_correlation_log(timestamp);

ALTER TABLE trades ADD COLUMN IF NOT EXISTS correlation_id VARCHAR(16);
ALTER TABLE trades ADD COLUMN IF NOT EXISTS initial_risk_points DECIMAL(10, 2);
