-- V7: Add missing signal_log table and fix tp1hit column name
CREATE TABLE IF NOT EXISTS signal_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    timestamp TIMESTAMP,
    spot DOUBLE PRECISION,
    vix DOUBLE PRECISION,
    support INTEGER,
    resistance INTEGER,
    confidence INTEGER,
    decision VARCHAR(50),
    reason VARCHAR(255)
);

-- Fix column name mismatch: Hibernate expects tp1_hit, V1 created tp1hit
DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_name='trades' AND column_name='tp1hit'
    ) AND NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_name='trades' AND column_name='tp1_hit'
    ) THEN
        ALTER TABLE trades RENAME COLUMN tp1hit TO tp1_hit;
    END IF;
END $$;
