spring:
  application:
    name: riskpilot
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true

# Core Background Daemon properly confidently elegantly tightly explicit precisely efficiently natively
spring:
  main:
    web-application-type: none

angelapi:
  key: ${ANGEL_API_KEY}
  clientcode: ${ANGEL_CLIENT_ID}
  pin: ${ANGEL_PIN}
  totp:
    secret: ${ANGEL_TOTP_SECRET}